apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: hypershift-install
  name: hypershift-install
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: hypershift
  name: hypershift
