apiVersion: v1
data:
  aws_cred: ZmFrZQ==
kind: Secret
metadata:
  name: external-dns
  namespace: hypershift
type: Opaque
---
apiVersion: v1
data:
  aws_cred: ZmFrZQ==
kind: Secret
metadata:
  name: oidc-discover
  namespace: hypershift
type: Opaque
