apiVersion: v2
name: hypershift-install
description: A Helm chart for installing Hypershift Operator on Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - hypershift
  - openshift
  - operator
